app/models.py
from datetime import datetime
from flask_sqlalchemy import SQLAlchemy


db = SQLAlchemy()


def configure_db(app):
    db.init_app(app)
    app.db = db


class Todo(db.Model):
    id = db.Column(
        db.Integer,
        unique=True,
        primary_key=True
    )
    task = db.Column(db.String(300))
    pub_date = db.Column(
        db.DateTime, nullable=False,
        default=datetime.utcnow
    )

    def __str__(self):
        return str(self.task)

    def __repr__(self):
        return str(self.task)

app/__init__.py
from flask import Flask
from flask_migrate import Migrate
# local imports
from app.config import Config
from app.models import configure_db


def create_app():

    app = Flask(__name__)
    app.config.from_object(Config)

    # configure dd
    configure_db(app=app)

    # set migrate to use with flask db init
    Migrate(app, app.db)

    # register blueprints
    from app.views import task
    app.register_blueprint(task)

    return app

app/views.py
from flask import (
    Blueprint,
    render_template,
    url_for,
    request,
    url_for,
    redirect,
    current_app
)

from app.models import Todo

task = Blueprint('task', __name__)


@task.route('/about', methods=['GET'])
def about():
    return render_template('index.html')


@task.route('/', methods=['GET', 'POST'])
def todo_app():
    if request.method == 'POST':
        if request.form['task']:
            new_todo = Todo(task=request.form['task'])
            current_app.db.session.add(new_todo)
            current_app.db.session.commit()
            return redirect(url_for('task.todo_app'))
    else:
        todos = Todo.query.all()
        return render_template(
            'index.html',
            todos=todos
        )


@task.route('/remove_task/<int:_id>', methods=['GET'])
def remove_task(_id=None):
    todo = Todo.query.filter_by(id=_id).first()
    current_app.db.session.delete(todo)
    current_app.db.session.commit()
    return redirect(url_for('task.todo_app'))

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0"
        />
        <meta http-equiv="X-UA-Compatible" content="ie=edge" />
        <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        />
        <title>Todo List</title>
    </head>

    <body>
        <div class="container">
            <br />
            <nav class="navbar navbar-dark bg-primary">
                <a class="navbar-brand" href="#">TodoApp</a>
            </nav>
            <br />
            <div class="jumbotron">
                <div class="form-group">
                    <form method="POST">
                        <label
                            class="text-center alert alert-danger"
                            for=""
                            >Adicione um novo item.</label
                        >
                        <input
                            type="text"
                            class="form-control"
                            placeholder="Ir as compras..."
                            name="task"
                        />
                    </form>
                </div>
            </div>
            <div class="">
                {% if todos %} {% for todo in todos %}
                <ul class="list-group">
                    <li class="list-group-item mb-2">
                        {{ todo.task }}
                        <a
                            href="{{ url_for('task.remove_task', _id=todo.id) }}"
                            class="
                                btn btn-outline-warning
                                float-right
                                btn-sm
                            "
                            >Deletar</a
                        >
                    </li>
                </ul>
                {% endfor %} {% else %}
                <h3 class="alert alert-warning text-center">
                    Lista Vazia, Adicione novos items...
                </h3>
                {% endif %}
            </div>
        </div>

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    </body>
</html>